added_location_hw
AliKonoplenko/homework_playwright pull request #3
Opened 2023-11-27 20:16 UTC by AliKonoplenko

2023-11-28 14:59 UTC, Densf2 requested changes

2023-11-28 14:59 UTC, Densf2 commented on tests/location.spec.js
> +test('location for britain', async ({ page }) => {
no location config

2023-11-28 15:08 UTC, AliKonoplenko commented on tests/location.spec.js
> +test('location for britain', async ({ page }) => {
added playwright.config.js

2023-11-28 17:57 UTC, merged

2023-11-30 06:18 UTC, Densf2 reviewed
good